export default {
  IS_APP_LOADED: 'IS_APP_LOADED',
  IS_SIGNUP_PROCESSING: 'IS_SIGNUP_PROCESSING',
  LOGOUT: 'LOGOUT',
  RESET_SIGNUP_ERRORS: 'RESET_SIGNUP_ERRORS',
  SET_USER: 'SET_USER',
  SET_SIGNUP_ERROR: 'SET_SIGNUP_ERROR',
  SET_ANSWERS_TO_CHECK: 'SET_ANSWER_TO_CHECK',
  REMOVE_ANSWER_FROM_ANSWER_TO_CHECK: 'REMOVE_ANSWER_FROM_ANSWER_TO_CHECK',
};
