export default {
  IS_APP_LOADED: 'IS_APP_LOADED',
  IS_SIGNIN_PROCESSING: 'IS_SIGNIN_PROCESSING',
  IS_SIGNUP_PROCESSING: 'IS_SIGNUP_PROCESSING',
  LOGOUT: 'LOGOUT',
  RESET_SIGNIN_ERRORS: 'RESET_SIGNIN_ERRORS',
  RESET_SIGNUP_ERRORS: 'RESET_SIGNUP_ERRORS',
  SET_USER: 'SET_USER',
  SET_SIGNIN_ERROR: 'SET_SIGNIN_ERROR',
  SET_SIGNUP_ERROR: 'SET_SIGNUP_ERROR',
  ADD_ANSWER_TO_CHECK: 'ADD_ANSWER_TO_CHECK',
  REMOVE_ANSWER_TO_CHECK: 'REMOVE_ANSWER_TO_CHECK',
  RESET_ANSWERS_TO_CHECK: 'RESET_ANSWERS_TO_CHECK',
};
