name: 'Build actions'
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@master
        run: npm build
      - name: 'Deploy indexes'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: '/home/runner/work/auchan-squid-game/auchan-squid-game/index.js,/home/runner/work/auchan-squid-game/auchan-squid-game/dist/index.html'
          target: ${{ secrets.SERVER_TARGET }}
          use_insecure_cipher: true
          debug: true
      - name: Check out repository
        uses: actions/checkout@master
        run: npm build
      - name: 'Deploy packaged files'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: '/home/runner/work/auchan-squid-game/auchan-squid-game/dist/*,/home/runner/work/auchan-squid-game/auchan-squid-game/dist/**/*'
          target: ${{ secrets.SERVER_PUBLIC_TARGET }}
          use_insecure_cipher: true
          debug: true
